title: A.J. Roetker
tagline: In Wonderland
owner: Andrew Roetker
link: https://github.com/ajroetker/
copyright: Copyright Andrew Roetker 2014-2016

hilighter: true
permalink: '/:title'
markdown: kramdown

exclude: [README.md]
